### ISSUE TITLE
TSC Error

### ISSUE THREAD

**Issue by robcresswell** [rcjsuen/dockerfile-ast#46]
Running `tsc` seems to cause build errors when consuming the library.

```
node_modules/dockerfile-ast/lib/main.d.ts:30:18 - error TS2430: Interface 'Dockerfile' incorrectly extends interface 'ImageTemplate'.
  Types of property 'resolveVariable' are incompatible.
    Type '(variable: string, line: number) => string | null | undefined' is not assignable to type '(variable: string, line: number) => string'.
      Type 'string | null | undefined' is not assignable to type 'string'.
        Type 'undefined' is not assignable to type 'string'.
```

**Comment by robcresswell** [comment]
I tried several: `3.1.6`, `2.9.2`, `2.8.4`

**Comment by robcresswell** [comment]
If I can help out further, I'd love to; this lib looks excellent so far.

**Comment by rcjsuen** [comment]
@robcresswell I'm pretty sure I know what the problem is. However, I'm unable to reproduce the problem. I removed my `package-lock.json` file and changed my `package.json` to point to your versions but did not get a compiler error while building the library or running `npm test`.

https://github.com/rcjsuen/dockerfile-ast/blob/02129618244055084d075ac2a62d3f167cbef9fc/package.json#L35

Perhaps my `tsconfig.json` file is not strict enough?

**Comment by rcjsuen** [comment]
Never mind, using `"strict": true` did the trick. :)

**Comment by rcjsuen** [comment]
@robcresswell Thank you for your bug report. I have fixed this in `master. You can review the fix by looking at 707320998bffc15fb40874b23fed868169938a01 if you wish.

To get around this for yourself in the immediate future, you can turn on `skipLibCheck` so that the TypeScript compiler doesn't try to check your dependent libraries.

**Comment by robcresswell** [comment]
That's awesome. Thanks for your help; any plans for an upcoming release?

**Comment by rcjsuen** [comment]
@robcresswell Not at the moment.

I think what I'd like to do is turn on `strict` and try to correct what it finds and then maybe cut a new release then. How does that sound to you?

**Comment by robcresswell** [comment]
Sounds great; if you'd like some help, please let me know. I know asking for changes in OSS can be a massive pain, so I don't want to demand your time by any means.

**Comment by rcjsuen** [comment]
@robcresswell No worries. You've already helped out by opening a bug. You're the first person to open a bug in this project. The other 45 before you were all opened by me! :)

If you have any suggestions, find something is unclear, or find another bug, let me know! The parsing of quoted strings, JSON, and `ARG` and `ENV` instructions are probably the most confusing but I imagine you won't be hitting those strange edge cases hopefully...
